baseURL = "https://barowik-portfolio.netlify.app"
title = "Portfolio"
author = "James Barowik"
copyright = "James Barowik"
paginate = 10
languageCode = "en"
theme = "tailwind"

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  [params.header]
    logo = "https://github.com/SilentSmeary/hugo/blob/master/images/logo.png?raw=true"

  [params.footer]
    since = 2024
    poweredby = true

[menu]
  [[menu.main]]
    identifier = "post"
    name = "Post"
    pageRef = "/posts"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"